services:
  postgres:
    platform: linux/x86_64
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    image: docker.io/postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MH_STORAGE=maildir
    volumes:
      - mail:/maildir
volumes:
  pgdata:
  mail: