site_name: Janus
site_url: https://janus.brictson.dev
repo_url: https://github.com/lbrictson/janus
edit_uri: edit/main/docs/
docs_dir: ./docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
  features:
    - content.action.edit
nav:
  - About: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
  - Understanding Jobs:
    - Creating Your First Job: understanding-jobs/creating-your-first-job.md
    - Versioning: understanding-jobs/versioning.md
    - Arguments: understanding-jobs/arguments.md
    - Environment Variables: understanding-jobs/environment-variables.md
    - Secrets: understanding-jobs/secrets.md
    - Scheduling: understanding-jobs/scheduling.md
    - Notifications: understanding-jobs/notifications.md
    - Webhook Trigger: understanding-jobs/webhooks.md
    - Advanced Settings: understanding-jobs/advanced-settings.md
  - User Management:
    - Global Roles: user-management/user-roles.md
    - User Permissions: user-management/user-permissions.md
  - Notifications:
    - Email: notifications/email.md
    - Slack: notifications/slack.md
    - Webhooks: notifications/webhooks.md
    - PagerDuty: notifications/pagerduty.md
    - Discord: notifications/discord.md
    - SMS (Twilio): notifications/twilio.md
    - AWS SNS: notifications/aws-sns.md
    - AWS EventBridge: notifications/aws-eventbridge.md
  - Configuration:
    - Runtime Config: configuration/runtime-config.md
    - Admin Config: configuration/admin-config.md
  - FAQ: faq.md