// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/janus/ent/authconfig"
)

// AuthConfigCreate is the builder for creating a AuthConfig entity.
type AuthConfigCreate struct {
	config
	mutation *AuthConfigMutation
	hooks    []Hook
}

// SetEnableSSO sets the "enable_sso" field.
func (acc *AuthConfigCreate) SetEnableSSO(b bool) *AuthConfigCreate {
	acc.mutation.SetEnableSSO(b)
	return acc
}

// SetNillableEnableSSO sets the "enable_sso" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableEnableSSO(b *bool) *AuthConfigCreate {
	if b != nil {
		acc.SetEnableSSO(*b)
	}
	return acc
}

// SetDisablePasswordLogin sets the "disable_password_login" field.
func (acc *AuthConfigCreate) SetDisablePasswordLogin(b bool) *AuthConfigCreate {
	acc.mutation.SetDisablePasswordLogin(b)
	return acc
}

// SetNillableDisablePasswordLogin sets the "disable_password_login" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableDisablePasswordLogin(b *bool) *AuthConfigCreate {
	if b != nil {
		acc.SetDisablePasswordLogin(*b)
	}
	return acc
}

// SetSSOProvider sets the "sso_provider" field.
func (acc *AuthConfigCreate) SetSSOProvider(s string) *AuthConfigCreate {
	acc.mutation.SetSSOProvider(s)
	return acc
}

// SetNillableSSOProvider sets the "sso_provider" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableSSOProvider(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetSSOProvider(*s)
	}
	return acc
}

// SetSSOClientID sets the "sso_client_id" field.
func (acc *AuthConfigCreate) SetSSOClientID(s string) *AuthConfigCreate {
	acc.mutation.SetSSOClientID(s)
	return acc
}

// SetNillableSSOClientID sets the "sso_client_id" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableSSOClientID(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetSSOClientID(*s)
	}
	return acc
}

// SetSSOClientSecret sets the "sso_client_secret" field.
func (acc *AuthConfigCreate) SetSSOClientSecret(s string) *AuthConfigCreate {
	acc.mutation.SetSSOClientSecret(s)
	return acc
}

// SetNillableSSOClientSecret sets the "sso_client_secret" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableSSOClientSecret(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetSSOClientSecret(*s)
	}
	return acc
}

// SetSSORedirectURI sets the "sso_redirect_uri" field.
func (acc *AuthConfigCreate) SetSSORedirectURI(s string) *AuthConfigCreate {
	acc.mutation.SetSSORedirectURI(s)
	return acc
}

// SetNillableSSORedirectURI sets the "sso_redirect_uri" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableSSORedirectURI(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetSSORedirectURI(*s)
	}
	return acc
}

// SetSSOAuthorizationURL sets the "sso_authorization_url" field.
func (acc *AuthConfigCreate) SetSSOAuthorizationURL(s string) *AuthConfigCreate {
	acc.mutation.SetSSOAuthorizationURL(s)
	return acc
}

// SetNillableSSOAuthorizationURL sets the "sso_authorization_url" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableSSOAuthorizationURL(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetSSOAuthorizationURL(*s)
	}
	return acc
}

// SetSSOTokenURL sets the "sso_token_url" field.
func (acc *AuthConfigCreate) SetSSOTokenURL(s string) *AuthConfigCreate {
	acc.mutation.SetSSOTokenURL(s)
	return acc
}

// SetNillableSSOTokenURL sets the "sso_token_url" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableSSOTokenURL(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetSSOTokenURL(*s)
	}
	return acc
}

// SetSSOUserInfoURL sets the "sso_user_info_url" field.
func (acc *AuthConfigCreate) SetSSOUserInfoURL(s string) *AuthConfigCreate {
	acc.mutation.SetSSOUserInfoURL(s)
	return acc
}

// SetNillableSSOUserInfoURL sets the "sso_user_info_url" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableSSOUserInfoURL(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetSSOUserInfoURL(*s)
	}
	return acc
}

// SetEntraTenantID sets the "entra_tenant_id" field.
func (acc *AuthConfigCreate) SetEntraTenantID(s string) *AuthConfigCreate {
	acc.mutation.SetEntraTenantID(s)
	return acc
}

// SetNillableEntraTenantID sets the "entra_tenant_id" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableEntraTenantID(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetEntraTenantID(*s)
	}
	return acc
}

// SetGoogleAllowedDomains sets the "google_allowed_domains" field.
func (acc *AuthConfigCreate) SetGoogleAllowedDomains(s string) *AuthConfigCreate {
	acc.mutation.SetGoogleAllowedDomains(s)
	return acc
}

// SetNillableGoogleAllowedDomains sets the "google_allowed_domains" field if the given value is not nil.
func (acc *AuthConfigCreate) SetNillableGoogleAllowedDomains(s *string) *AuthConfigCreate {
	if s != nil {
		acc.SetGoogleAllowedDomains(*s)
	}
	return acc
}

// SetSessionKey sets the "session_key" field.
func (acc *AuthConfigCreate) SetSessionKey(b []byte) *AuthConfigCreate {
	acc.mutation.SetSessionKey(b)
	return acc
}

// Mutation returns the AuthConfigMutation object of the builder.
func (acc *AuthConfigCreate) Mutation() *AuthConfigMutation {
	return acc.mutation
}

// Save creates the AuthConfig in the database.
func (acc *AuthConfigCreate) Save(ctx context.Context) (*AuthConfig, error) {
	acc.defaults()
	return withHooks(ctx, acc.sqlSave, acc.mutation, acc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (acc *AuthConfigCreate) SaveX(ctx context.Context) *AuthConfig {
	v, err := acc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acc *AuthConfigCreate) Exec(ctx context.Context) error {
	_, err := acc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acc *AuthConfigCreate) ExecX(ctx context.Context) {
	if err := acc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (acc *AuthConfigCreate) defaults() {
	if _, ok := acc.mutation.EnableSSO(); !ok {
		v := authconfig.DefaultEnableSSO
		acc.mutation.SetEnableSSO(v)
	}
	if _, ok := acc.mutation.DisablePasswordLogin(); !ok {
		v := authconfig.DefaultDisablePasswordLogin
		acc.mutation.SetDisablePasswordLogin(v)
	}
	if _, ok := acc.mutation.SSOProvider(); !ok {
		v := authconfig.DefaultSSOProvider
		acc.mutation.SetSSOProvider(v)
	}
	if _, ok := acc.mutation.SSOClientID(); !ok {
		v := authconfig.DefaultSSOClientID
		acc.mutation.SetSSOClientID(v)
	}
	if _, ok := acc.mutation.SSOClientSecret(); !ok {
		v := authconfig.DefaultSSOClientSecret
		acc.mutation.SetSSOClientSecret(v)
	}
	if _, ok := acc.mutation.SSORedirectURI(); !ok {
		v := authconfig.DefaultSSORedirectURI
		acc.mutation.SetSSORedirectURI(v)
	}
	if _, ok := acc.mutation.SSOAuthorizationURL(); !ok {
		v := authconfig.DefaultSSOAuthorizationURL
		acc.mutation.SetSSOAuthorizationURL(v)
	}
	if _, ok := acc.mutation.SSOTokenURL(); !ok {
		v := authconfig.DefaultSSOTokenURL
		acc.mutation.SetSSOTokenURL(v)
	}
	if _, ok := acc.mutation.SSOUserInfoURL(); !ok {
		v := authconfig.DefaultSSOUserInfoURL
		acc.mutation.SetSSOUserInfoURL(v)
	}
	if _, ok := acc.mutation.EntraTenantID(); !ok {
		v := authconfig.DefaultEntraTenantID
		acc.mutation.SetEntraTenantID(v)
	}
	if _, ok := acc.mutation.GoogleAllowedDomains(); !ok {
		v := authconfig.DefaultGoogleAllowedDomains
		acc.mutation.SetGoogleAllowedDomains(v)
	}
	if _, ok := acc.mutation.SessionKey(); !ok {
		v := authconfig.DefaultSessionKey
		acc.mutation.SetSessionKey(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acc *AuthConfigCreate) check() error {
	if _, ok := acc.mutation.EnableSSO(); !ok {
		return &ValidationError{Name: "enable_sso", err: errors.New(`ent: missing required field "AuthConfig.enable_sso"`)}
	}
	if _, ok := acc.mutation.DisablePasswordLogin(); !ok {
		return &ValidationError{Name: "disable_password_login", err: errors.New(`ent: missing required field "AuthConfig.disable_password_login"`)}
	}
	if _, ok := acc.mutation.SSOProvider(); !ok {
		return &ValidationError{Name: "sso_provider", err: errors.New(`ent: missing required field "AuthConfig.sso_provider"`)}
	}
	if _, ok := acc.mutation.SSOClientID(); !ok {
		return &ValidationError{Name: "sso_client_id", err: errors.New(`ent: missing required field "AuthConfig.sso_client_id"`)}
	}
	if _, ok := acc.mutation.SSOClientSecret(); !ok {
		return &ValidationError{Name: "sso_client_secret", err: errors.New(`ent: missing required field "AuthConfig.sso_client_secret"`)}
	}
	if _, ok := acc.mutation.SSORedirectURI(); !ok {
		return &ValidationError{Name: "sso_redirect_uri", err: errors.New(`ent: missing required field "AuthConfig.sso_redirect_uri"`)}
	}
	if _, ok := acc.mutation.SSOAuthorizationURL(); !ok {
		return &ValidationError{Name: "sso_authorization_url", err: errors.New(`ent: missing required field "AuthConfig.sso_authorization_url"`)}
	}
	if _, ok := acc.mutation.SSOTokenURL(); !ok {
		return &ValidationError{Name: "sso_token_url", err: errors.New(`ent: missing required field "AuthConfig.sso_token_url"`)}
	}
	if _, ok := acc.mutation.SSOUserInfoURL(); !ok {
		return &ValidationError{Name: "sso_user_info_url", err: errors.New(`ent: missing required field "AuthConfig.sso_user_info_url"`)}
	}
	if _, ok := acc.mutation.EntraTenantID(); !ok {
		return &ValidationError{Name: "entra_tenant_id", err: errors.New(`ent: missing required field "AuthConfig.entra_tenant_id"`)}
	}
	if _, ok := acc.mutation.GoogleAllowedDomains(); !ok {
		return &ValidationError{Name: "google_allowed_domains", err: errors.New(`ent: missing required field "AuthConfig.google_allowed_domains"`)}
	}
	if _, ok := acc.mutation.SessionKey(); !ok {
		return &ValidationError{Name: "session_key", err: errors.New(`ent: missing required field "AuthConfig.session_key"`)}
	}
	return nil
}

func (acc *AuthConfigCreate) sqlSave(ctx context.Context) (*AuthConfig, error) {
	if err := acc.check(); err != nil {
		return nil, err
	}
	_node, _spec := acc.createSpec()
	if err := sqlgraph.CreateNode(ctx, acc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	acc.mutation.id = &_node.ID
	acc.mutation.done = true
	return _node, nil
}

func (acc *AuthConfigCreate) createSpec() (*AuthConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthConfig{config: acc.config}
		_spec = sqlgraph.NewCreateSpec(authconfig.Table, sqlgraph.NewFieldSpec(authconfig.FieldID, field.TypeInt))
	)
	if value, ok := acc.mutation.EnableSSO(); ok {
		_spec.SetField(authconfig.FieldEnableSSO, field.TypeBool, value)
		_node.EnableSSO = value
	}
	if value, ok := acc.mutation.DisablePasswordLogin(); ok {
		_spec.SetField(authconfig.FieldDisablePasswordLogin, field.TypeBool, value)
		_node.DisablePasswordLogin = value
	}
	if value, ok := acc.mutation.SSOProvider(); ok {
		_spec.SetField(authconfig.FieldSSOProvider, field.TypeString, value)
		_node.SSOProvider = value
	}
	if value, ok := acc.mutation.SSOClientID(); ok {
		_spec.SetField(authconfig.FieldSSOClientID, field.TypeString, value)
		_node.SSOClientID = value
	}
	if value, ok := acc.mutation.SSOClientSecret(); ok {
		_spec.SetField(authconfig.FieldSSOClientSecret, field.TypeString, value)
		_node.SSOClientSecret = value
	}
	if value, ok := acc.mutation.SSORedirectURI(); ok {
		_spec.SetField(authconfig.FieldSSORedirectURI, field.TypeString, value)
		_node.SSORedirectURI = value
	}
	if value, ok := acc.mutation.SSOAuthorizationURL(); ok {
		_spec.SetField(authconfig.FieldSSOAuthorizationURL, field.TypeString, value)
		_node.SSOAuthorizationURL = value
	}
	if value, ok := acc.mutation.SSOTokenURL(); ok {
		_spec.SetField(authconfig.FieldSSOTokenURL, field.TypeString, value)
		_node.SSOTokenURL = value
	}
	if value, ok := acc.mutation.SSOUserInfoURL(); ok {
		_spec.SetField(authconfig.FieldSSOUserInfoURL, field.TypeString, value)
		_node.SSOUserInfoURL = value
	}
	if value, ok := acc.mutation.EntraTenantID(); ok {
		_spec.SetField(authconfig.FieldEntraTenantID, field.TypeString, value)
		_node.EntraTenantID = value
	}
	if value, ok := acc.mutation.GoogleAllowedDomains(); ok {
		_spec.SetField(authconfig.FieldGoogleAllowedDomains, field.TypeString, value)
		_node.GoogleAllowedDomains = value
	}
	if value, ok := acc.mutation.SessionKey(); ok {
		_spec.SetField(authconfig.FieldSessionKey, field.TypeBytes, value)
		_node.SessionKey = value
	}
	return _node, _spec
}

// AuthConfigCreateBulk is the builder for creating many AuthConfig entities in bulk.
type AuthConfigCreateBulk struct {
	config
	err      error
	builders []*AuthConfigCreate
}

// Save creates the AuthConfig entities in the database.
func (accb *AuthConfigCreateBulk) Save(ctx context.Context) ([]*AuthConfig, error) {
	if accb.err != nil {
		return nil, accb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(accb.builders))
	nodes := make([]*AuthConfig, len(accb.builders))
	mutators := make([]Mutator, len(accb.builders))
	for i := range accb.builders {
		func(i int, root context.Context) {
			builder := accb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, accb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, accb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, accb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (accb *AuthConfigCreateBulk) SaveX(ctx context.Context) []*AuthConfig {
	v, err := accb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (accb *AuthConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := accb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (accb *AuthConfigCreateBulk) ExecX(ctx context.Context) {
	if err := accb.Exec(ctx); err != nil {
		panic(err)
	}
}
