// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/janus/ent/dataconfig"
	"github.com/lbrictson/janus/ent/predicate"
)

// DataConfigUpdate is the builder for updating DataConfig entities.
type DataConfigUpdate struct {
	config
	hooks    []Hook
	mutation *DataConfigMutation
}

// Where appends a list predicates to the DataConfigUpdate builder.
func (_u *DataConfigUpdate) Where(ps ...predicate.DataConfig) *DataConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDaysToKeep sets the "days_to_keep" field.
func (_u *DataConfigUpdate) SetDaysToKeep(v int) *DataConfigUpdate {
	_u.mutation.ResetDaysToKeep()
	_u.mutation.SetDaysToKeep(v)
	return _u
}

// SetNillableDaysToKeep sets the "days_to_keep" field if the given value is not nil.
func (_u *DataConfigUpdate) SetNillableDaysToKeep(v *int) *DataConfigUpdate {
	if v != nil {
		_u.SetDaysToKeep(*v)
	}
	return _u
}

// AddDaysToKeep adds value to the "days_to_keep" field.
func (_u *DataConfigUpdate) AddDaysToKeep(v int) *DataConfigUpdate {
	_u.mutation.AddDaysToKeep(v)
	return _u
}

// Mutation returns the DataConfigMutation object of the builder.
func (_u *DataConfigUpdate) Mutation() *DataConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DataConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DataConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DataConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DataConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DataConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dataconfig.Table, dataconfig.Columns, sqlgraph.NewFieldSpec(dataconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DaysToKeep(); ok {
		_spec.SetField(dataconfig.FieldDaysToKeep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDaysToKeep(); ok {
		_spec.AddField(dataconfig.FieldDaysToKeep, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dataconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DataConfigUpdateOne is the builder for updating a single DataConfig entity.
type DataConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DataConfigMutation
}

// SetDaysToKeep sets the "days_to_keep" field.
func (_u *DataConfigUpdateOne) SetDaysToKeep(v int) *DataConfigUpdateOne {
	_u.mutation.ResetDaysToKeep()
	_u.mutation.SetDaysToKeep(v)
	return _u
}

// SetNillableDaysToKeep sets the "days_to_keep" field if the given value is not nil.
func (_u *DataConfigUpdateOne) SetNillableDaysToKeep(v *int) *DataConfigUpdateOne {
	if v != nil {
		_u.SetDaysToKeep(*v)
	}
	return _u
}

// AddDaysToKeep adds value to the "days_to_keep" field.
func (_u *DataConfigUpdateOne) AddDaysToKeep(v int) *DataConfigUpdateOne {
	_u.mutation.AddDaysToKeep(v)
	return _u
}

// Mutation returns the DataConfigMutation object of the builder.
func (_u *DataConfigUpdateOne) Mutation() *DataConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the DataConfigUpdate builder.
func (_u *DataConfigUpdateOne) Where(ps ...predicate.DataConfig) *DataConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DataConfigUpdateOne) Select(field string, fields ...string) *DataConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DataConfig entity.
func (_u *DataConfigUpdateOne) Save(ctx context.Context) (*DataConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DataConfigUpdateOne) SaveX(ctx context.Context) *DataConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DataConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DataConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DataConfigUpdateOne) sqlSave(ctx context.Context) (_node *DataConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(dataconfig.Table, dataconfig.Columns, sqlgraph.NewFieldSpec(dataconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DataConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dataconfig.FieldID)
		for _, f := range fields {
			if !dataconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dataconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DaysToKeep(); ok {
		_spec.SetField(dataconfig.FieldDaysToKeep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDaysToKeep(); ok {
		_spec.AddField(dataconfig.FieldDaysToKeep, field.TypeInt, value)
	}
	_node = &DataConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dataconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
