// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lbrictson/janus/ent/dataconfig"
)

// DataConfig is the model entity for the DataConfig schema.
type DataConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DaysToKeep holds the value of the "days_to_keep" field.
	DaysToKeep   int `json:"days_to_keep,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DataConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dataconfig.FieldID, dataconfig.FieldDaysToKeep:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DataConfig fields.
func (_m *DataConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dataconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dataconfig.FieldDaysToKeep:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field days_to_keep", values[i])
			} else if value.Valid {
				_m.DaysToKeep = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DataConfig.
// This includes values selected through modifiers, order, etc.
func (_m *DataConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DataConfig.
// Note that you need to call DataConfig.Unwrap() before calling this method if this DataConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DataConfig) Update() *DataConfigUpdateOne {
	return NewDataConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DataConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DataConfig) Unwrap() *DataConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DataConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DataConfig) String() string {
	var builder strings.Builder
	builder.WriteString("DataConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("days_to_keep=")
	builder.WriteString(fmt.Sprintf("%v", _m.DaysToKeep))
	builder.WriteByte(')')
	return builder.String()
}

// DataConfigs is a parsable slice of DataConfig.
type DataConfigs []*DataConfig
