// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/janus/ent/jobconfig"
	"github.com/lbrictson/janus/ent/predicate"
)

// JobConfigDelete is the builder for deleting a JobConfig entity.
type JobConfigDelete struct {
	config
	hooks    []Hook
	mutation *JobConfigMutation
}

// Where appends a list predicates to the JobConfigDelete builder.
func (jcd *JobConfigDelete) Where(ps ...predicate.JobConfig) *JobConfigDelete {
	jcd.mutation.Where(ps...)
	return jcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jcd *JobConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, jcd.sqlExec, jcd.mutation, jcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (jcd *JobConfigDelete) ExecX(ctx context.Context) int {
	n, err := jcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jcd *JobConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jobconfig.Table, sqlgraph.NewFieldSpec(jobconfig.FieldID, field.TypeInt))
	if ps := jcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, jcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	jcd.mutation.done = true
	return affected, err
}

// JobConfigDeleteOne is the builder for deleting a single JobConfig entity.
type JobConfigDeleteOne struct {
	jcd *JobConfigDelete
}

// Where appends a list predicates to the JobConfigDelete builder.
func (jcdo *JobConfigDeleteOne) Where(ps ...predicate.JobConfig) *JobConfigDeleteOne {
	jcdo.jcd.mutation.Where(ps...)
	return jcdo
}

// Exec executes the deletion query.
func (jcdo *JobConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := jcdo.jcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jobconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jcdo *JobConfigDeleteOne) ExecX(ctx context.Context) {
	if err := jcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
