// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/janus/ent/jobhistory"
	"github.com/lbrictson/janus/ent/predicate"
)

// JobHistoryDelete is the builder for deleting a JobHistory entity.
type JobHistoryDelete struct {
	config
	hooks    []Hook
	mutation *JobHistoryMutation
}

// Where appends a list predicates to the JobHistoryDelete builder.
func (jhd *JobHistoryDelete) Where(ps ...predicate.JobHistory) *JobHistoryDelete {
	jhd.mutation.Where(ps...)
	return jhd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jhd *JobHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, jhd.sqlExec, jhd.mutation, jhd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (jhd *JobHistoryDelete) ExecX(ctx context.Context) int {
	n, err := jhd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jhd *JobHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(jobhistory.Table, sqlgraph.NewFieldSpec(jobhistory.FieldID, field.TypeInt))
	if ps := jhd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, jhd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	jhd.mutation.done = true
	return affected, err
}

// JobHistoryDeleteOne is the builder for deleting a single JobHistory entity.
type JobHistoryDeleteOne struct {
	jhd *JobHistoryDelete
}

// Where appends a list predicates to the JobHistoryDelete builder.
func (jhdo *JobHistoryDeleteOne) Where(ps ...predicate.JobHistory) *JobHistoryDeleteOne {
	jhdo.jhd.mutation.Where(ps...)
	return jhdo
}

// Exec executes the deletion query.
func (jhdo *JobHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := jhdo.jhd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jobhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jhdo *JobHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := jhdo.Exec(ctx); err != nil {
		panic(err)
	}
}
