// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/janus/ent/predicate"
	"github.com/lbrictson/janus/ent/project"
	"github.com/lbrictson/janus/ent/projectuser"
	"github.com/lbrictson/janus/ent/user"
)

// ProjectUserUpdate is the builder for updating ProjectUser entities.
type ProjectUserUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectUserMutation
}

// Where appends a list predicates to the ProjectUserUpdate builder.
func (puu *ProjectUserUpdate) Where(ps ...predicate.ProjectUser) *ProjectUserUpdate {
	puu.mutation.Where(ps...)
	return puu
}

// SetCanEdit sets the "can_edit" field.
func (puu *ProjectUserUpdate) SetCanEdit(b bool) *ProjectUserUpdate {
	puu.mutation.SetCanEdit(b)
	return puu
}

// SetNillableCanEdit sets the "can_edit" field if the given value is not nil.
func (puu *ProjectUserUpdate) SetNillableCanEdit(b *bool) *ProjectUserUpdate {
	if b != nil {
		puu.SetCanEdit(*b)
	}
	return puu
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (puu *ProjectUserUpdate) SetProjectID(id int) *ProjectUserUpdate {
	puu.mutation.SetProjectID(id)
	return puu
}

// SetProject sets the "project" edge to the Project entity.
func (puu *ProjectUserUpdate) SetProject(p *Project) *ProjectUserUpdate {
	return puu.SetProjectID(p.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (puu *ProjectUserUpdate) SetUserID(id int) *ProjectUserUpdate {
	puu.mutation.SetUserID(id)
	return puu
}

// SetUser sets the "user" edge to the User entity.
func (puu *ProjectUserUpdate) SetUser(u *User) *ProjectUserUpdate {
	return puu.SetUserID(u.ID)
}

// Mutation returns the ProjectUserMutation object of the builder.
func (puu *ProjectUserUpdate) Mutation() *ProjectUserMutation {
	return puu.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (puu *ProjectUserUpdate) ClearProject() *ProjectUserUpdate {
	puu.mutation.ClearProject()
	return puu
}

// ClearUser clears the "user" edge to the User entity.
func (puu *ProjectUserUpdate) ClearUser() *ProjectUserUpdate {
	puu.mutation.ClearUser()
	return puu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (puu *ProjectUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, puu.sqlSave, puu.mutation, puu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puu *ProjectUserUpdate) SaveX(ctx context.Context) int {
	affected, err := puu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (puu *ProjectUserUpdate) Exec(ctx context.Context) error {
	_, err := puu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puu *ProjectUserUpdate) ExecX(ctx context.Context) {
	if err := puu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puu *ProjectUserUpdate) check() error {
	if puu.mutation.ProjectCleared() && len(puu.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectUser.project"`)
	}
	if puu.mutation.UserCleared() && len(puu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectUser.user"`)
	}
	return nil
}

func (puu *ProjectUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := puu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectuser.Table, projectuser.Columns, sqlgraph.NewFieldSpec(projectuser.FieldID, field.TypeInt))
	if ps := puu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puu.mutation.CanEdit(); ok {
		_spec.SetField(projectuser.FieldCanEdit, field.TypeBool, value)
	}
	if puu.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectuser.ProjectTable,
			Columns: []string{projectuser.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puu.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectuser.ProjectTable,
			Columns: []string{projectuser.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectuser.UserTable,
			Columns: []string{projectuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectuser.UserTable,
			Columns: []string{projectuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, puu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	puu.mutation.done = true
	return n, nil
}

// ProjectUserUpdateOne is the builder for updating a single ProjectUser entity.
type ProjectUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectUserMutation
}

// SetCanEdit sets the "can_edit" field.
func (puuo *ProjectUserUpdateOne) SetCanEdit(b bool) *ProjectUserUpdateOne {
	puuo.mutation.SetCanEdit(b)
	return puuo
}

// SetNillableCanEdit sets the "can_edit" field if the given value is not nil.
func (puuo *ProjectUserUpdateOne) SetNillableCanEdit(b *bool) *ProjectUserUpdateOne {
	if b != nil {
		puuo.SetCanEdit(*b)
	}
	return puuo
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (puuo *ProjectUserUpdateOne) SetProjectID(id int) *ProjectUserUpdateOne {
	puuo.mutation.SetProjectID(id)
	return puuo
}

// SetProject sets the "project" edge to the Project entity.
func (puuo *ProjectUserUpdateOne) SetProject(p *Project) *ProjectUserUpdateOne {
	return puuo.SetProjectID(p.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (puuo *ProjectUserUpdateOne) SetUserID(id int) *ProjectUserUpdateOne {
	puuo.mutation.SetUserID(id)
	return puuo
}

// SetUser sets the "user" edge to the User entity.
func (puuo *ProjectUserUpdateOne) SetUser(u *User) *ProjectUserUpdateOne {
	return puuo.SetUserID(u.ID)
}

// Mutation returns the ProjectUserMutation object of the builder.
func (puuo *ProjectUserUpdateOne) Mutation() *ProjectUserMutation {
	return puuo.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (puuo *ProjectUserUpdateOne) ClearProject() *ProjectUserUpdateOne {
	puuo.mutation.ClearProject()
	return puuo
}

// ClearUser clears the "user" edge to the User entity.
func (puuo *ProjectUserUpdateOne) ClearUser() *ProjectUserUpdateOne {
	puuo.mutation.ClearUser()
	return puuo
}

// Where appends a list predicates to the ProjectUserUpdate builder.
func (puuo *ProjectUserUpdateOne) Where(ps ...predicate.ProjectUser) *ProjectUserUpdateOne {
	puuo.mutation.Where(ps...)
	return puuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puuo *ProjectUserUpdateOne) Select(field string, fields ...string) *ProjectUserUpdateOne {
	puuo.fields = append([]string{field}, fields...)
	return puuo
}

// Save executes the query and returns the updated ProjectUser entity.
func (puuo *ProjectUserUpdateOne) Save(ctx context.Context) (*ProjectUser, error) {
	return withHooks(ctx, puuo.sqlSave, puuo.mutation, puuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puuo *ProjectUserUpdateOne) SaveX(ctx context.Context) *ProjectUser {
	node, err := puuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puuo *ProjectUserUpdateOne) Exec(ctx context.Context) error {
	_, err := puuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puuo *ProjectUserUpdateOne) ExecX(ctx context.Context) {
	if err := puuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puuo *ProjectUserUpdateOne) check() error {
	if puuo.mutation.ProjectCleared() && len(puuo.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectUser.project"`)
	}
	if puuo.mutation.UserCleared() && len(puuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectUser.user"`)
	}
	return nil
}

func (puuo *ProjectUserUpdateOne) sqlSave(ctx context.Context) (_node *ProjectUser, err error) {
	if err := puuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectuser.Table, projectuser.Columns, sqlgraph.NewFieldSpec(projectuser.FieldID, field.TypeInt))
	id, ok := puuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectuser.FieldID)
		for _, f := range fields {
			if !projectuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puuo.mutation.CanEdit(); ok {
		_spec.SetField(projectuser.FieldCanEdit, field.TypeBool, value)
	}
	if puuo.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectuser.ProjectTable,
			Columns: []string{projectuser.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puuo.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectuser.ProjectTable,
			Columns: []string{projectuser.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectuser.UserTable,
			Columns: []string{projectuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectuser.UserTable,
			Columns: []string{projectuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectUser{config: puuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puuo.mutation.done = true
	return _node, nil
}
