// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lbrictson/janus/ent/authconfig"
	"github.com/lbrictson/janus/ent/dataconfig"
	"github.com/lbrictson/janus/ent/inboundwebhook"
	"github.com/lbrictson/janus/ent/job"
	"github.com/lbrictson/janus/ent/jobconfig"
	"github.com/lbrictson/janus/ent/jobhistory"
	"github.com/lbrictson/janus/ent/jobversion"
	"github.com/lbrictson/janus/ent/notificationchannel"
	"github.com/lbrictson/janus/ent/projectuser"
	"github.com/lbrictson/janus/ent/schema"
	"github.com/lbrictson/janus/ent/secret"
	"github.com/lbrictson/janus/ent/smtpconfig"
	"github.com/lbrictson/janus/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authconfigFields := schema.AuthConfig{}.Fields()
	_ = authconfigFields
	// authconfigDescEnableSSO is the schema descriptor for enable_sso field.
	authconfigDescEnableSSO := authconfigFields[0].Descriptor()
	// authconfig.DefaultEnableSSO holds the default value on creation for the enable_sso field.
	authconfig.DefaultEnableSSO = authconfigDescEnableSSO.Default.(bool)
	// authconfigDescDisablePasswordLogin is the schema descriptor for disable_password_login field.
	authconfigDescDisablePasswordLogin := authconfigFields[1].Descriptor()
	// authconfig.DefaultDisablePasswordLogin holds the default value on creation for the disable_password_login field.
	authconfig.DefaultDisablePasswordLogin = authconfigDescDisablePasswordLogin.Default.(bool)
	// authconfigDescSSOProvider is the schema descriptor for sso_provider field.
	authconfigDescSSOProvider := authconfigFields[2].Descriptor()
	// authconfig.DefaultSSOProvider holds the default value on creation for the sso_provider field.
	authconfig.DefaultSSOProvider = authconfigDescSSOProvider.Default.(string)
	// authconfigDescSSOClientID is the schema descriptor for sso_client_id field.
	authconfigDescSSOClientID := authconfigFields[3].Descriptor()
	// authconfig.DefaultSSOClientID holds the default value on creation for the sso_client_id field.
	authconfig.DefaultSSOClientID = authconfigDescSSOClientID.Default.(string)
	// authconfigDescSSOClientSecret is the schema descriptor for sso_client_secret field.
	authconfigDescSSOClientSecret := authconfigFields[4].Descriptor()
	// authconfig.DefaultSSOClientSecret holds the default value on creation for the sso_client_secret field.
	authconfig.DefaultSSOClientSecret = authconfigDescSSOClientSecret.Default.(string)
	// authconfigDescSSORedirectURI is the schema descriptor for sso_redirect_uri field.
	authconfigDescSSORedirectURI := authconfigFields[5].Descriptor()
	// authconfig.DefaultSSORedirectURI holds the default value on creation for the sso_redirect_uri field.
	authconfig.DefaultSSORedirectURI = authconfigDescSSORedirectURI.Default.(string)
	// authconfigDescSSOAuthorizationURL is the schema descriptor for sso_authorization_url field.
	authconfigDescSSOAuthorizationURL := authconfigFields[6].Descriptor()
	// authconfig.DefaultSSOAuthorizationURL holds the default value on creation for the sso_authorization_url field.
	authconfig.DefaultSSOAuthorizationURL = authconfigDescSSOAuthorizationURL.Default.(string)
	// authconfigDescSSOTokenURL is the schema descriptor for sso_token_url field.
	authconfigDescSSOTokenURL := authconfigFields[7].Descriptor()
	// authconfig.DefaultSSOTokenURL holds the default value on creation for the sso_token_url field.
	authconfig.DefaultSSOTokenURL = authconfigDescSSOTokenURL.Default.(string)
	// authconfigDescSSOUserInfoURL is the schema descriptor for sso_user_info_url field.
	authconfigDescSSOUserInfoURL := authconfigFields[8].Descriptor()
	// authconfig.DefaultSSOUserInfoURL holds the default value on creation for the sso_user_info_url field.
	authconfig.DefaultSSOUserInfoURL = authconfigDescSSOUserInfoURL.Default.(string)
	// authconfigDescEntraTenantID is the schema descriptor for entra_tenant_id field.
	authconfigDescEntraTenantID := authconfigFields[9].Descriptor()
	// authconfig.DefaultEntraTenantID holds the default value on creation for the entra_tenant_id field.
	authconfig.DefaultEntraTenantID = authconfigDescEntraTenantID.Default.(string)
	// authconfigDescGoogleAllowedDomains is the schema descriptor for google_allowed_domains field.
	authconfigDescGoogleAllowedDomains := authconfigFields[10].Descriptor()
	// authconfig.DefaultGoogleAllowedDomains holds the default value on creation for the google_allowed_domains field.
	authconfig.DefaultGoogleAllowedDomains = authconfigDescGoogleAllowedDomains.Default.(string)
	// authconfigDescSessionKey is the schema descriptor for session_key field.
	authconfigDescSessionKey := authconfigFields[11].Descriptor()
	// authconfig.DefaultSessionKey holds the default value on creation for the session_key field.
	authconfig.DefaultSessionKey = authconfigDescSessionKey.Default.([]byte)
	dataconfigFields := schema.DataConfig{}.Fields()
	_ = dataconfigFields
	// dataconfigDescDaysToKeep is the schema descriptor for days_to_keep field.
	dataconfigDescDaysToKeep := dataconfigFields[0].Descriptor()
	// dataconfig.DefaultDaysToKeep holds the default value on creation for the days_to_keep field.
	dataconfig.DefaultDaysToKeep = dataconfigDescDaysToKeep.Default.(int)
	inboundwebhookFields := schema.InboundWebhook{}.Fields()
	_ = inboundwebhookFields
	// inboundwebhookDescCreatedAt is the schema descriptor for created_at field.
	inboundwebhookDescCreatedAt := inboundwebhookFields[2].Descriptor()
	// inboundwebhook.DefaultCreatedAt holds the default value on creation for the created_at field.
	inboundwebhook.DefaultCreatedAt = inboundwebhookDescCreatedAt.Default.(func() time.Time)
	// inboundwebhookDescRequireAPIKey is the schema descriptor for require_api_key field.
	inboundwebhookDescRequireAPIKey := inboundwebhookFields[3].Descriptor()
	// inboundwebhook.DefaultRequireAPIKey holds the default value on creation for the require_api_key field.
	inboundwebhook.DefaultRequireAPIKey = inboundwebhookDescRequireAPIKey.Default.(bool)
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescName is the schema descriptor for name field.
	jobDescName := jobFields[0].Descriptor()
	// job.NameValidator is a validator for the "name" field. It is called by the builders before save.
	job.NameValidator = jobDescName.Validators[0].(func(string) error)
	// jobDescScheduleEnabled is the schema descriptor for schedule_enabled field.
	jobDescScheduleEnabled := jobFields[3].Descriptor()
	// job.DefaultScheduleEnabled holds the default value on creation for the schedule_enabled field.
	job.DefaultScheduleEnabled = jobDescScheduleEnabled.Default.(bool)
	// jobDescAllowConcurrentRuns is the schema descriptor for allow_concurrent_runs field.
	jobDescAllowConcurrentRuns := jobFields[4].Descriptor()
	// job.DefaultAllowConcurrentRuns holds the default value on creation for the allow_concurrent_runs field.
	job.DefaultAllowConcurrentRuns = jobDescAllowConcurrentRuns.Default.(bool)
	// jobDescRequiresFileUpload is the schema descriptor for requires_file_upload field.
	jobDescRequiresFileUpload := jobFields[6].Descriptor()
	// job.DefaultRequiresFileUpload holds the default value on creation for the requires_file_upload field.
	job.DefaultRequiresFileUpload = jobDescRequiresFileUpload.Default.(bool)
	// jobDescAverageDurationMs is the schema descriptor for average_duration_ms field.
	jobDescAverageDurationMs := jobFields[7].Descriptor()
	// job.DefaultAverageDurationMs holds the default value on creation for the average_duration_ms field.
	job.DefaultAverageDurationMs = jobDescAverageDurationMs.Default.(int64)
	// jobDescTimeoutSeconds is the schema descriptor for timeout_seconds field.
	jobDescTimeoutSeconds := jobFields[8].Descriptor()
	// job.DefaultTimeoutSeconds holds the default value on creation for the timeout_seconds field.
	job.DefaultTimeoutSeconds = jobDescTimeoutSeconds.Default.(int)
	// jobDescLastEditTime is the schema descriptor for last_edit_time field.
	jobDescLastEditTime := jobFields[9].Descriptor()
	// job.UpdateDefaultLastEditTime holds the default value on update for the last_edit_time field.
	job.UpdateDefaultLastEditTime = jobDescLastEditTime.UpdateDefault.(func() time.Time)
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[10].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
	// jobDescLastRunSuccess is the schema descriptor for last_run_success field.
	jobDescLastRunSuccess := jobFields[17].Descriptor()
	// job.DefaultLastRunSuccess holds the default value on creation for the last_run_success field.
	job.DefaultLastRunSuccess = jobDescLastRunSuccess.Default.(bool)
	// jobDescCreatedByAPI is the schema descriptor for created_by_api field.
	jobDescCreatedByAPI := jobFields[18].Descriptor()
	// job.DefaultCreatedByAPI holds the default value on creation for the created_by_api field.
	job.DefaultCreatedByAPI = jobDescCreatedByAPI.Default.(bool)
	jobconfigFields := schema.JobConfig{}.Fields()
	_ = jobconfigFields
	// jobconfigDescMaxConcurrentJobs is the schema descriptor for max_concurrent_jobs field.
	jobconfigDescMaxConcurrentJobs := jobconfigFields[0].Descriptor()
	// jobconfig.DefaultMaxConcurrentJobs holds the default value on creation for the max_concurrent_jobs field.
	jobconfig.DefaultMaxConcurrentJobs = jobconfigDescMaxConcurrentJobs.Default.(int)
	// jobconfigDescDefaultTimeoutSeconds is the schema descriptor for default_timeout_seconds field.
	jobconfigDescDefaultTimeoutSeconds := jobconfigFields[1].Descriptor()
	// jobconfig.DefaultDefaultTimeoutSeconds holds the default value on creation for the default_timeout_seconds field.
	jobconfig.DefaultDefaultTimeoutSeconds = jobconfigDescDefaultTimeoutSeconds.Default.(int)
	jobhistoryFields := schema.JobHistory{}.Fields()
	_ = jobhistoryFields
	// jobhistoryDescOutput is the schema descriptor for output field.
	jobhistoryDescOutput := jobhistoryFields[3].Descriptor()
	// jobhistory.DefaultOutput holds the default value on creation for the output field.
	jobhistory.DefaultOutput = jobhistoryDescOutput.Default.(string)
	// jobhistoryDescCreatedAt is the schema descriptor for created_at field.
	jobhistoryDescCreatedAt := jobhistoryFields[7].Descriptor()
	// jobhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	jobhistory.DefaultCreatedAt = jobhistoryDescCreatedAt.Default.(func() time.Time)
	// jobhistoryDescStatus is the schema descriptor for status field.
	jobhistoryDescStatus := jobhistoryFields[8].Descriptor()
	// jobhistory.DefaultStatus holds the default value on creation for the status field.
	jobhistory.DefaultStatus = jobhistoryDescStatus.Default.(string)
	// jobhistoryDescTrigger is the schema descriptor for trigger field.
	jobhistoryDescTrigger := jobhistoryFields[9].Descriptor()
	// jobhistory.DefaultTrigger holds the default value on creation for the trigger field.
	jobhistory.DefaultTrigger = jobhistoryDescTrigger.Default.(string)
	jobversionFields := schema.JobVersion{}.Fields()
	_ = jobversionFields
	// jobversionDescCreatedAt is the schema descriptor for created_at field.
	jobversionDescCreatedAt := jobversionFields[0].Descriptor()
	// jobversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	jobversion.DefaultCreatedAt = jobversionDescCreatedAt.Default.(func() time.Time)
	notificationchannelFields := schema.NotificationChannel{}.Fields()
	_ = notificationchannelFields
	// notificationchannelDescName is the schema descriptor for name field.
	notificationchannelDescName := notificationchannelFields[0].Descriptor()
	// notificationchannel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	notificationchannel.NameValidator = notificationchannelDescName.Validators[0].(func(string) error)
	// notificationchannelDescCreatedAt is the schema descriptor for created_at field.
	notificationchannelDescCreatedAt := notificationchannelFields[4].Descriptor()
	// notificationchannel.DefaultCreatedAt holds the default value on creation for the created_at field.
	notificationchannel.DefaultCreatedAt = notificationchannelDescCreatedAt.Default.(func() time.Time)
	// notificationchannelDescUpdatedAt is the schema descriptor for updated_at field.
	notificationchannelDescUpdatedAt := notificationchannelFields[5].Descriptor()
	// notificationchannel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notificationchannel.DefaultUpdatedAt = notificationchannelDescUpdatedAt.Default.(func() time.Time)
	// notificationchannel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notificationchannel.UpdateDefaultUpdatedAt = notificationchannelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationchannelDescEnabled is the schema descriptor for enabled field.
	notificationchannelDescEnabled := notificationchannelFields[6].Descriptor()
	// notificationchannel.DefaultEnabled holds the default value on creation for the enabled field.
	notificationchannel.DefaultEnabled = notificationchannelDescEnabled.Default.(bool)
	// notificationchannelDescRetryCount is the schema descriptor for retry_count field.
	notificationchannelDescRetryCount := notificationchannelFields[7].Descriptor()
	// notificationchannel.DefaultRetryCount holds the default value on creation for the retry_count field.
	notificationchannel.DefaultRetryCount = notificationchannelDescRetryCount.Default.(int)
	projectuserFields := schema.ProjectUser{}.Fields()
	_ = projectuserFields
	// projectuserDescCanEdit is the schema descriptor for can_edit field.
	projectuserDescCanEdit := projectuserFields[0].Descriptor()
	// projectuser.DefaultCanEdit holds the default value on creation for the can_edit field.
	projectuser.DefaultCanEdit = projectuserDescCanEdit.Default.(bool)
	smtpconfigFields := schema.SMTPConfig{}.Fields()
	_ = smtpconfigFields
	// smtpconfigDescSMTPServer is the schema descriptor for smtp_server field.
	smtpconfigDescSMTPServer := smtpconfigFields[0].Descriptor()
	// smtpconfig.DefaultSMTPServer holds the default value on creation for the smtp_server field.
	smtpconfig.DefaultSMTPServer = smtpconfigDescSMTPServer.Default.(string)
	// smtpconfigDescSMTPPort is the schema descriptor for smtp_port field.
	smtpconfigDescSMTPPort := smtpconfigFields[1].Descriptor()
	// smtpconfig.DefaultSMTPPort holds the default value on creation for the smtp_port field.
	smtpconfig.DefaultSMTPPort = smtpconfigDescSMTPPort.Default.(int)
	// smtpconfigDescSMTPUsername is the schema descriptor for smtp_username field.
	smtpconfigDescSMTPUsername := smtpconfigFields[2].Descriptor()
	// smtpconfig.DefaultSMTPUsername holds the default value on creation for the smtp_username field.
	smtpconfig.DefaultSMTPUsername = smtpconfigDescSMTPUsername.Default.(string)
	// smtpconfigDescSMTPPassword is the schema descriptor for smtp_password field.
	smtpconfigDescSMTPPassword := smtpconfigFields[3].Descriptor()
	// smtpconfig.DefaultSMTPPassword holds the default value on creation for the smtp_password field.
	smtpconfig.DefaultSMTPPassword = smtpconfigDescSMTPPassword.Default.(string)
	// smtpconfigDescSMTPSender is the schema descriptor for smtp_sender field.
	smtpconfigDescSMTPSender := smtpconfigFields[4].Descriptor()
	// smtpconfig.DefaultSMTPSender holds the default value on creation for the smtp_sender field.
	smtpconfig.DefaultSMTPSender = smtpconfigDescSMTPSender.Default.(string)
	// smtpconfigDescSMTPTLS is the schema descriptor for smtp_tls field.
	smtpconfigDescSMTPTLS := smtpconfigFields[5].Descriptor()
	// smtpconfig.DefaultSMTPTLS holds the default value on creation for the smtp_tls field.
	smtpconfig.DefaultSMTPTLS = smtpconfigDescSMTPTLS.Default.(bool)
	secretFields := schema.Secret{}.Fields()
	_ = secretFields
	// secretDescCreatedAt is the schema descriptor for created_at field.
	secretDescCreatedAt := secretFields[2].Descriptor()
	// secret.DefaultCreatedAt holds the default value on creation for the created_at field.
	secret.DefaultCreatedAt = secretDescCreatedAt.Default.(func() time.Time)
	// secretDescUpdatedAt is the schema descriptor for updated_at field.
	secretDescUpdatedAt := secretFields[3].Descriptor()
	// secret.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	secret.DefaultUpdatedAt = secretDescUpdatedAt.Default.(func() time.Time)
	// secret.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	secret.UpdateDefaultUpdatedAt = secretDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAdmin is the schema descriptor for admin field.
	userDescAdmin := userFields[2].Descriptor()
	// user.DefaultAdmin holds the default value on creation for the admin field.
	user.DefaultAdmin = userDescAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescMustChangePassword is the schema descriptor for must_change_password field.
	userDescMustChangePassword := userFields[6].Descriptor()
	// user.DefaultMustChangePassword holds the default value on creation for the must_change_password field.
	user.DefaultMustChangePassword = userDescMustChangePassword.Default.(bool)
	// userDescIsSSO is the schema descriptor for is_sso field.
	userDescIsSSO := userFields[7].Descriptor()
	// user.DefaultIsSSO holds the default value on creation for the is_sso field.
	user.DefaultIsSSO = userDescIsSSO.Default.(bool)
}
