// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lbrictson/janus/ent/smtpconfig"
)

// SMTPConfigCreate is the builder for creating a SMTPConfig entity.
type SMTPConfigCreate struct {
	config
	mutation *SMTPConfigMutation
	hooks    []Hook
}

// SetSMTPServer sets the "smtp_server" field.
func (_c *SMTPConfigCreate) SetSMTPServer(v string) *SMTPConfigCreate {
	_c.mutation.SetSMTPServer(v)
	return _c
}

// SetNillableSMTPServer sets the "smtp_server" field if the given value is not nil.
func (_c *SMTPConfigCreate) SetNillableSMTPServer(v *string) *SMTPConfigCreate {
	if v != nil {
		_c.SetSMTPServer(*v)
	}
	return _c
}

// SetSMTPPort sets the "smtp_port" field.
func (_c *SMTPConfigCreate) SetSMTPPort(v int) *SMTPConfigCreate {
	_c.mutation.SetSMTPPort(v)
	return _c
}

// SetNillableSMTPPort sets the "smtp_port" field if the given value is not nil.
func (_c *SMTPConfigCreate) SetNillableSMTPPort(v *int) *SMTPConfigCreate {
	if v != nil {
		_c.SetSMTPPort(*v)
	}
	return _c
}

// SetSMTPUsername sets the "smtp_username" field.
func (_c *SMTPConfigCreate) SetSMTPUsername(v string) *SMTPConfigCreate {
	_c.mutation.SetSMTPUsername(v)
	return _c
}

// SetNillableSMTPUsername sets the "smtp_username" field if the given value is not nil.
func (_c *SMTPConfigCreate) SetNillableSMTPUsername(v *string) *SMTPConfigCreate {
	if v != nil {
		_c.SetSMTPUsername(*v)
	}
	return _c
}

// SetSMTPPassword sets the "smtp_password" field.
func (_c *SMTPConfigCreate) SetSMTPPassword(v string) *SMTPConfigCreate {
	_c.mutation.SetSMTPPassword(v)
	return _c
}

// SetNillableSMTPPassword sets the "smtp_password" field if the given value is not nil.
func (_c *SMTPConfigCreate) SetNillableSMTPPassword(v *string) *SMTPConfigCreate {
	if v != nil {
		_c.SetSMTPPassword(*v)
	}
	return _c
}

// SetSMTPSender sets the "smtp_sender" field.
func (_c *SMTPConfigCreate) SetSMTPSender(v string) *SMTPConfigCreate {
	_c.mutation.SetSMTPSender(v)
	return _c
}

// SetNillableSMTPSender sets the "smtp_sender" field if the given value is not nil.
func (_c *SMTPConfigCreate) SetNillableSMTPSender(v *string) *SMTPConfigCreate {
	if v != nil {
		_c.SetSMTPSender(*v)
	}
	return _c
}

// SetSMTPTLS sets the "smtp_tls" field.
func (_c *SMTPConfigCreate) SetSMTPTLS(v bool) *SMTPConfigCreate {
	_c.mutation.SetSMTPTLS(v)
	return _c
}

// SetNillableSMTPTLS sets the "smtp_tls" field if the given value is not nil.
func (_c *SMTPConfigCreate) SetNillableSMTPTLS(v *bool) *SMTPConfigCreate {
	if v != nil {
		_c.SetSMTPTLS(*v)
	}
	return _c
}

// Mutation returns the SMTPConfigMutation object of the builder.
func (_c *SMTPConfigCreate) Mutation() *SMTPConfigMutation {
	return _c.mutation
}

// Save creates the SMTPConfig in the database.
func (_c *SMTPConfigCreate) Save(ctx context.Context) (*SMTPConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SMTPConfigCreate) SaveX(ctx context.Context) *SMTPConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SMTPConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SMTPConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SMTPConfigCreate) defaults() {
	if _, ok := _c.mutation.SMTPServer(); !ok {
		v := smtpconfig.DefaultSMTPServer
		_c.mutation.SetSMTPServer(v)
	}
	if _, ok := _c.mutation.SMTPPort(); !ok {
		v := smtpconfig.DefaultSMTPPort
		_c.mutation.SetSMTPPort(v)
	}
	if _, ok := _c.mutation.SMTPUsername(); !ok {
		v := smtpconfig.DefaultSMTPUsername
		_c.mutation.SetSMTPUsername(v)
	}
	if _, ok := _c.mutation.SMTPPassword(); !ok {
		v := smtpconfig.DefaultSMTPPassword
		_c.mutation.SetSMTPPassword(v)
	}
	if _, ok := _c.mutation.SMTPSender(); !ok {
		v := smtpconfig.DefaultSMTPSender
		_c.mutation.SetSMTPSender(v)
	}
	if _, ok := _c.mutation.SMTPTLS(); !ok {
		v := smtpconfig.DefaultSMTPTLS
		_c.mutation.SetSMTPTLS(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SMTPConfigCreate) check() error {
	if _, ok := _c.mutation.SMTPServer(); !ok {
		return &ValidationError{Name: "smtp_server", err: errors.New(`ent: missing required field "SMTPConfig.smtp_server"`)}
	}
	if _, ok := _c.mutation.SMTPPort(); !ok {
		return &ValidationError{Name: "smtp_port", err: errors.New(`ent: missing required field "SMTPConfig.smtp_port"`)}
	}
	if _, ok := _c.mutation.SMTPUsername(); !ok {
		return &ValidationError{Name: "smtp_username", err: errors.New(`ent: missing required field "SMTPConfig.smtp_username"`)}
	}
	if _, ok := _c.mutation.SMTPPassword(); !ok {
		return &ValidationError{Name: "smtp_password", err: errors.New(`ent: missing required field "SMTPConfig.smtp_password"`)}
	}
	if _, ok := _c.mutation.SMTPSender(); !ok {
		return &ValidationError{Name: "smtp_sender", err: errors.New(`ent: missing required field "SMTPConfig.smtp_sender"`)}
	}
	if _, ok := _c.mutation.SMTPTLS(); !ok {
		return &ValidationError{Name: "smtp_tls", err: errors.New(`ent: missing required field "SMTPConfig.smtp_tls"`)}
	}
	return nil
}

func (_c *SMTPConfigCreate) sqlSave(ctx context.Context) (*SMTPConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SMTPConfigCreate) createSpec() (*SMTPConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &SMTPConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(smtpconfig.Table, sqlgraph.NewFieldSpec(smtpconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SMTPServer(); ok {
		_spec.SetField(smtpconfig.FieldSMTPServer, field.TypeString, value)
		_node.SMTPServer = value
	}
	if value, ok := _c.mutation.SMTPPort(); ok {
		_spec.SetField(smtpconfig.FieldSMTPPort, field.TypeInt, value)
		_node.SMTPPort = value
	}
	if value, ok := _c.mutation.SMTPUsername(); ok {
		_spec.SetField(smtpconfig.FieldSMTPUsername, field.TypeString, value)
		_node.SMTPUsername = value
	}
	if value, ok := _c.mutation.SMTPPassword(); ok {
		_spec.SetField(smtpconfig.FieldSMTPPassword, field.TypeString, value)
		_node.SMTPPassword = value
	}
	if value, ok := _c.mutation.SMTPSender(); ok {
		_spec.SetField(smtpconfig.FieldSMTPSender, field.TypeString, value)
		_node.SMTPSender = value
	}
	if value, ok := _c.mutation.SMTPTLS(); ok {
		_spec.SetField(smtpconfig.FieldSMTPTLS, field.TypeBool, value)
		_node.SMTPTLS = value
	}
	return _node, _spec
}

// SMTPConfigCreateBulk is the builder for creating many SMTPConfig entities in bulk.
type SMTPConfigCreateBulk struct {
	config
	err      error
	builders []*SMTPConfigCreate
}

// Save creates the SMTPConfig entities in the database.
func (_c *SMTPConfigCreateBulk) Save(ctx context.Context) ([]*SMTPConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SMTPConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SMTPConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SMTPConfigCreateBulk) SaveX(ctx context.Context) []*SMTPConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SMTPConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SMTPConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
