// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// AuthConfig is the predicate function for authconfig builders.
type AuthConfig func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// JobHistory is the predicate function for jobhistory builders.
type JobHistory func(*sql.Selector)

// NotificationChannel is the predicate function for notificationchannel builders.
type NotificationChannel func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectUser is the predicate function for projectuser builders.
type ProjectUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
